sonar.projectKey=incidentflow-plus
sonar.projectName=IncidentFlow
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.test.inclusions=backend/tests/**/*.js,frontend/tests/**/*.js,frontend/tests/**/*.jsx
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/*.log,deploy/proxy/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
